name: Build Translation File
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Merge Locale Files
        uses: larrrssss/i18n-merge@v0.1.1
        id: merge
        with:
          workspace: ${{ github.workspace }}
      - name: Push to build branch
        if: ${{ steps.merge.outputs.changes_detected == '1' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add .
          git commit -m "chore: update build output"
          git push